# Generated by Django 6.0.7 on 2026-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slarule',
            old_name='response_hours',
            new_name='response_minutes',
        ),
        migrations.AddField(
            model_name='slarule',
            name='coverage',
            field=models.CharField(default='24/7', max_length=50),
        ),
    ]
