# Generated by Django 6.0.7 on 2026-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_department_severityrule_team_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('sub_category', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='Enterprise IT Knowledge Base', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='priority',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='resolution_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='response_hours',
            field=models.IntegerField(default=4),
        ),
    ]
