# Generated by Django 6.0.7 on 2026-08-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_rename_response_hours_slarule_response_minutes_and_more'),
        ('masterdata', '0003_knowledgearticle_alter_priority_code_and_more'),
    ]

    operations = [
    ]
