# Generated by Django 6.0.7 on 2026-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_rename_response_hours_slarule_response_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='resolution_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='response_minutes',
            field=models.IntegerField(),
        ),
    ]
