# Generated by Django 6.0.7 on 2026-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Support Manager'), ('Agent', 'Agent'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
