# Generated by Django 6.0.7 on 2026-09-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Working / Available'), ('BUSY', 'Busy'), ('UNAVAILABLE', 'Not Working / Unavailable'), ('INACTIVE', 'Inactive')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('IT Department', 'IT Department'), ('HR Department', 'HR Department'), ('Finance Department', 'Finance Department'), ('Operations', 'Operations')], db_index=True, default='IT Department', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, default='Support Specialist', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
