import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getAllTickets } from "../../services/ticketService";

export default function AgentDashboard() {
  const [tickets, setTickets] = useState([]);
  useEffect(() => setTickets(getAllTickets()), []);
  const open = tickets.filter((ticket) => !["Resolved", "Closed"].includes(ticket.status));
  const classified = tickets.filter((ticket) => ticket.ai);
  const categories = tickets.reduce((result, ticket) => { const key = ticket.category || "UNCLASSIFIED"; result[key] = (result[key] || 0) + 1; return result; }, {});
  const max = Math.max(1, ...Object.values(categories));
  return <div><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Tickets received today", tickets.length, "Live ticket volume"], ["Classified automatically", classified.length, `${tickets.length ? Math.round(classified.length / tickets.length * 100) : 0}% coverage`], ["Open tickets", open.length, "Require attention"], ["SLA at risk", open.filter((ticket) => ticket.priority === "High").length, "High priority"]].map(([label, value, detail]) => <div className="sp-card p-4" key={label}><div className="text-[11px] font-semibold text-[#8b95a1]">{label}</div><div className="my-1 text-2xl font-extrabold">{value}</div><div className="text-[11px] text-[#15803d]">{detail}</div></div>)}</div><div className="grid gap-3 lg:grid-cols-2"><section className="sp-card"><div className="sp-card-header"><h2>Classification health</h2><span className="sp-tag sp-tag-success">Meeting target</span></div><div className="sp-card-body">{[["Category accuracy (hold-out)", "94%"], ["Severity accuracy (hold-out)", "87%"], ["Avg confidence", "0.88"], ["Routed to LLM path", "18%"], ["Agent overrides today", "0"], ["Unclassified", `${tickets.length - classified.length}`]].map(([label, value]) => <div className="flex justify-between border-b border-dashed border-[#eef2f0] py-2 text-xs last:border-0" key={label}><span className="text-[#4b5563]">{label}</span><strong>{value}</strong></div>)}</div></section><section className="sp-card"><div className="sp-card-header"><h2>Volume by category - today</h2><Link className="text-xs font-semibold text-[#14532d]" to="/tickets">View all</Link></div><div className="sp-card-body space-y-3">{Object.entries(categories).map(([category, count]) => <div key={category}><div className="mb-1 flex justify-between text-[11px]"><span>{category.toUpperCase()}</span><strong>{count}</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-[#eef2f0]"><div className="h-full rounded-full bg-[#1f7a45]" style={{ width: `${count / max * 100}%` }} /></div></div>)}{!Object.keys(categories).length && <div className="text-xs text-[#8b95a1]">No ticket data yet.</div>}</div></section></div></div>;
}
