# Generated by Django 6.0.7 on 2026-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='affected_scope',
            field=models.CharField(choices=[('SELF', 'Just me'), ('TEAM', 'My team'), ('DEPARTMENT', 'My department'), ('ORG_WIDE', 'Whole organisation')], default='SELF', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='channel',
            field=models.CharField(default='PORTAL', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='work_blocked',
            field=models.CharField(choices=[('YES', 'Yes'), ('PARTIAL', 'Partially'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workaround_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='UNCLASSIFIED', max_length=100),
        ),
    ]
