# Generated by Django 6.0.7 on 2026-08-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_affected_scope_ticket_asset_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
