# Generated by Django 6.0.7 on 2026-08-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_ticket_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='affected_scope',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='asset_tag',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='contact_preference',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='department',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='site',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_due_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='work_blocked',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='workaround_available',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
