# Generated by Django 6.0.7 on 2026-08-26 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_ticket_severity_ticket_sub_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workflow_status', models.CharField(choices=[('Started', 'Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Escalated', 'Escalated'), ('Failed', 'Failed')], default='Started', max_length=20)),
                ('current_agent', models.CharField(choices=[('Orchestrator', 'Orchestrator'), ('Diagnosis', 'Diagnosis'), ('Knowledge Retrieval', 'Knowledge Retrieval'), ('Resolution', 'Resolution'), ('Escalation', 'Escalation')], default='Orchestrator', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_confidence', models.FloatField(blank=True, null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflow', to='support.ticket')),
            ],
        ),
    ]
