# Generated by Django 6.0.7 on 2026-08-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_ticket_assigned_to_ticket_attachment_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS support_agentexecution;
            DROP TABLE IF EXISTS support_agentworkflow;
            DROP TABLE IF EXISTS support_emaillog;
            DROP TABLE IF EXISTS support_jiraticket;
            DROP TABLE IF EXISTS support_activitylog;
            """,
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CLASSIFIED', 'CLASSIFIED'), ('AI_PROCESSING', 'AI_PROCESSING'), ('AI_RESOLUTION_READY', 'AI_RESOLUTION_READY'), ('AI_RESOLVED', 'AI_RESOLVED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ESCALATED', 'ESCALATED'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('Open', 'Open'), ('Classified', 'Classified'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='NEW', max_length=30),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('actor', models.CharField(default='System', max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='support.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('workflow_status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('ESCALATED', 'ESCALATED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('current_agent', models.CharField(default='Orchestrator', max_length=64)),
                ('final_confidence', models.FloatField(default=0.0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflows', to='support.ticket')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('agent_name', models.CharField(max_length=64)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='support.agentworkflow')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('ticket_created', 'Ticket Received'), ('resolution', 'AI Resolution Ready'), ('escalation', 'Escalation Notice'), ('resolved', 'Ticket Resolved')], max_length=50)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='SENT', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='support.ticket')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('jira_issue_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('jira_issue_id', models.CharField(blank=True, default='', max_length=50)),
                ('jira_status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ESCALATED', 'ESCALATED'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=30)),
                ('jira_priority', models.CharField(default='Medium', max_length=20)),
                ('assignee', models.CharField(blank=True, default='', max_length=150)),
                ('team', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_tickets', to='support.ticket')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
    ]
