# Generated by Django 6.0.7 on 2026-08-26 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_agentworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agent_name', models.CharField(choices=[('Orchestrator', 'Orchestrator'), ('Diagnosis', 'Diagnosis'), ('Knowledge Retrieval', 'Knowledge Retrieval'), ('Resolution', 'Resolution'), ('Escalation', 'Escalation')], max_length=30)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Started', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='support.agentworkflow')),
            ],
        ),
    ]
