# Generated by Django 6.0.7 on 2026-09-03 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_ticket_status_activitylog_agentworkflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_analysis_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_queue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='auto_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEUTRAL', 'NEUTRAL'), ('NEGATIVE', 'NEGATIVE'), ('HIGHLY_FRUSTRATED', 'HIGHLY_FRUSTRATED')], default='NEUTRAL', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='similar_tickets_meta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_resolution_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_response_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='suggested_resolution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('DRAFT', 'DRAFT'), ('AI_ANALYZING', 'AI_ANALYZING'), ('AI_RESPONDED', 'AI_RESPONDED'), ('ASSIGNED', 'ASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('WAITING_FOR_CUSTOMER', 'WAITING_FOR_CUSTOMER'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('ESCALATED', 'ESCALATED'), ('REOPENED', 'REOPENED'), ('NEW', 'NEW'), ('CLASSIFIED', 'CLASSIFIED'), ('AI_PROCESSING', 'AI_PROCESSING'), ('AI_RESOLUTION_READY', 'AI_RESOLUTION_READY'), ('AI_RESOLVED', 'AI_RESOLVED'), ('Open', 'Open'), ('Classified', 'Classified'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ticket_created', 'New Ticket'), ('ai_response', 'AI Response'), ('assignment', 'Ticket Assignment'), ('escalation', 'Ticket Escalation'), ('agent_response', 'Agent Response'), ('customer_reply', 'Customer Reply'), ('sla_warning', 'SLA Warning'), ('sla_breach', 'SLA Breach'), ('resolved', 'Ticket Resolved'), ('closed', 'Ticket Closed'), ('reopened', 'Ticket Reopened'), ('system', 'System Alert')], default='system', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='support.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
