# Generated by Django 6.0.7 on 2026-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_ticket_ai_analysis_meta_ticket_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(db_index=True, default='IT Department', max_length=100),
        ),
    ]
