# Generated by Django 6.0.7 on 2026-09-09 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_ticket_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M4PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_response_threshold', models.FloatField(default=0.9)),
                ('agent_review_threshold', models.FloatField(default=0.7)),
                ('escalate_threshold', models.FloatField(default=0.7)),
                ('sensitive_categories', models.JSONField(blank=True, default=list)),
                ('allow_autonomous_send', models.BooleanField(default=False)),
                ('auto_close_days', models.IntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('DRAFT', 'DRAFT'), ('AI_ANALYZING', 'AI_ANALYZING'), ('AI_RESPONDED', 'AI_RESPONDED'), ('ASSIGNED', 'ASSIGNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('WAITING_FOR_CUSTOMER', 'WAITING_FOR_CUSTOMER'), ('AWAITING_CUSTOMER_INFO', 'AWAITING_CUSTOMER_INFO'), ('PENDING_AGENT_REVIEW', 'PENDING_AGENT_REVIEW'), ('PENDING_CONFIRMATION', 'PENDING_CONFIRMATION'), ('ON_HOLD', 'ON_HOLD'), ('RESOLVED', 'RESOLVED'), ('CLOSED', 'CLOSED'), ('ESCALATED', 'ESCALATED'), ('REOPENED', 'REOPENED'), ('NEW', 'NEW'), ('CLASSIFIED', 'CLASSIFIED'), ('AI_PROCESSING', 'AI_PROCESSING'), ('AI_RESOLUTION_READY', 'AI_RESOLUTION_READY'), ('AI_RESOLVED', 'AI_RESOLVED'), ('Open', 'Open'), ('Classified', 'Classified'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='OPEN', max_length=30),
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('agent_name', models.CharField(default='Support Agent', max_length=150)),
                ('action', models.CharField(choices=[('SEND_AI_RESPONSE', 'Send AI Response'), ('EDIT_AND_SEND', 'Edit & Send'), ('MANUAL_RESPONSE', 'Manual Response'), ('REQUEST_INFO', 'Request Info'), ('ESCALATE', 'Escalate'), ('RESOLVE', 'Resolve'), ('CLOSE', 'Close')], max_length=50)),
                ('checklist_results', models.JSONField(blank=True, default=dict)),
                ('original_suggestion', models.TextField(blank=True, default='')),
                ('final_response', models.TextField(blank=True, default='')),
                ('is_edited', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reviews', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m4_reviews', to='support.ticket')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('customer_name', models.CharField(default='Customer', max_length=150)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='m4_feedback', to='support.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('from_team', models.CharField(default='Tier-1 Frontline', max_length=100)),
                ('to_team', models.CharField(max_length=100)),
                ('assigned_specialist', models.CharField(blank=True, default='', max_length=150)),
                ('reason', models.TextField()),
                ('escalated_by', models.CharField(default='Agent', max_length=150)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m4_escalations', to='support.ticket')),
            ],
            options={
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('actor_name', models.CharField(default='System', max_length=150)),
                ('actor_role', models.CharField(default='System', max_length=50)),
                ('action', models.CharField(default='STATUS_CHANGE', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m4_status_history', to='support.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
