# Generated by Django 6.0.7 on 2026-09-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_m4policyconfig_alter_ticket_status_agentreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P1 - Critical', 'P1 - Critical'), ('P1 – Critical', 'P1 – Critical'), ('P2 - High', 'P2 - High'), ('P2 – High', 'P2 – High'), ('P3 - Medium', 'P3 - Medium'), ('P3 – Medium', 'P3 – Medium'), ('P4 - Low', 'P4 - Low'), ('P4 – Low', 'P4 – Low')], default='Medium', max_length=40),
        ),
    ]
