# Generated by Django 6.0.7 on 2026-09-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_alter_ticket_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEmailAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(default='default', max_length=50, unique=True)),
                ('open_enabled', models.BooleanField(default=True)),
                ('in_progress_enabled', models.BooleanField(default=True)),
                ('pending_enabled', models.BooleanField(default=True)),
                ('solved_enabled', models.BooleanField(default=True)),
                ('closed_enabled', models.BooleanField(default=True)),
                ('auto_send_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaillog',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='trigger_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(default='acknowledgement', max_length=50),
        ),
    ]
