# Generated by Django 6.0.7 on 2026-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_aiemailautomationconfig_emaillog_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemailautomationconfig',
            name='from_email',
            field=models.CharField(blank=True, default='SupportPilot <onboarding@resend.dev>', max_length=255),
        ),
        migrations.AddField(
            model_name='aiemailautomationconfig',
            name='resend_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
