# Generated by Django 6.0.7 on 2026-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_aiemailautomationconfig_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiemailautomationconfig',
            name='brevo_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
